// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLtigKfXqqp9Kd3lVmFgGkYtOgNkQ0RxM',
    appId: '1:798457368770:android:70ebf81089720eba052b5b',
    messagingSenderId: '798457368770',
    projectId: 'clone-e15bb',
    storageBucket: 'clone-e15bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyAnwSx8uWXjAa3nOWrQiHzoduvzbIKQA',
    appId: '1:798457368770:ios:315c1630cd24f3d5052b5b',
    messagingSenderId: '798457368770',
    projectId: 'clone-e15bb',
    storageBucket: 'clone-e15bb.firebasestorage.app',
    androidClientId: '798457368770-ohcml8lgebtt124tq64vrrrbhjtp67p6.apps.googleusercontent.com',
    iosClientId: '798457368770-rjhieea5ckh5kp8slr7hb6o78a9f6i78.apps.googleusercontent.com',
    iosBundleId: 'com.example.youtubeClone',
  );

}